### ISSUE TITLE
Siddhi gpl-execution-geo not working in java 18 environment.

### ISSUE THREAD

**Issue by Rakshithg19** [wso2-extensions/siddhi-gpl-execution-geo#43]
java.lang.NoClassDefFoundError: Could not initialize class org.wso2.extension.siddhi.gpl.execution.geo.internal.util.GeometryUtils
	at org.wso2.extension.siddhi.gpl.execution.geo.internal.util.GeoOperation.process(GeoOperation.java:66) ~[?:?]
	at org.wso2.extension.siddhi.gpl.execution.geo.function.AbstractGeoOperationExecutor.execute(AbstractGeoOperationExecutor.java:58) ~[?:?]
	at io.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:100) ~[?:?]
	at io.siddhi.core.executor.condition.BoolConditionExpressionExecutor.execute(BoolConditionExpressionExecutor.java:44) ~[?:?]
	at io.siddhi.core.executor.condition.BoolConditionExpressionExecutor.execute(BoolConditionExpressionExecutor.java:29) ~[?:?]
	at io.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:41) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.processNoGroupBy(QuerySelector.java:173) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:88) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.extension.execution.json.JsonTokenizerAsObjectStreamProcessorFunction.process(JsonTokenizerAsObjectStreamProcessorFunction.java:180) ~[?:?]
	at io.siddhi.core.query.processor.stream.StreamProcessor.processEventChunk(StreamProcessor.java:41) ~[?:?]
	at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:133) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.core.query.processor.filter.FilterProcessor.process(FilterProcessor.java:58) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:166) ~[?:?]
	at io.siddhi.core.util.event.handler.StreamHandler.onEvent(StreamHandler.java:65) ~[?:?]
	at io.siddhi.core.util.event.handler.StreamHandler.onEvent(StreamHandler.java:34) ~[?:?]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor_3.4.2.wso2v1.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor_3.4.2.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: com.vividsolutions.jts.geom.GeometryFactory is not an ImageIO SPI class [in thread "Siddhi-redishupdate-executor-thread-0"]
	at javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:712) ~[?:?]
	at javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117) ~[?:?]
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155) ~[?:?]
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:91) ~[?:?]
	at org.geotools.geometry.jts.JTSFactoryFinder.getServiceRegistry(JTSFactoryFinder.java:67) ~[?:?]
	at org.geotools.geometry.jts.JTSFactoryFinder.getGeometryFactory(JTSFactoryFinder.java:90) ~[?:?]
	at org.geotools.geometry.jts.JTSFactoryFinder.getGeometryFactory(JTSFactoryFinder.java:102) ~[?:?]
	at org.wso2.extension.siddhi.gpl.execution.geo.internal.util.GeometryUtils.<clinit>(GeometryUtils.java:42) ~[?:?]
	at org.wso2.extension.siddhi.gpl.execution.geo.internal.util.GeoOperation.process(GeoOperation.java:66) ~[?:?]
	at org.wso2.extension.siddhi.gpl.execution.geo.function.AbstractGeoOperationExecutor.execute(AbstractGeoOperationExecutor.java:58) ~[?:?]
	at io.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:100) ~[?:?]
	at io.siddhi.core.executor.condition.BoolConditionExpressionExecutor.execute(BoolConditionExpressionExecutor.java:44) ~[?:?]
	at io.siddhi.core.executor.condition.BoolConditionExpressionExecutor.execute(BoolConditionExpressionExecutor.java:29) ~[?:?]
	at io.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:41) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.processNoGroupBy(QuerySelector.java:173) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:88) ~[?:?]
	at io.siddhi.core.query.processor.stream.LogStreamProcessor.process(LogStreamProcessor.java:276) ~[?:?]
	at io.siddhi.core.query.processor.stream.StreamProcessor.processEventChunk(StreamProcessor.java:41) ~[?:?]
	at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:133) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:115) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:180) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:497) ~[?:?]
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104) ~[?:?]
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:45) ~[?:?]
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) ~[?:?]
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:127) ~[?:?]
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:203) ~[?:?]
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:506) ~[?:?]
	at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34) ~[?:?]
	at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:45) ~[?:?]
	at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:79) ~[?:?]
	at io.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35) ~[?:?]
	at io.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:83) ~[?:?]
	at io.siddhi.extension.map.json.sourcemapper.JsonSourceMapper.mapAndProcess(JsonSourceMapper.java:256) ~[?:?]
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:201) ~[?:?]
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:154) ~[?:?]
	at io.siddhi.extension.io.kafka.source.KafkaConsumerThread.run(KafkaConsumerThread.java:243) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	... 3 more

**Comment by Rakshithg19** [comment]
Please help me solve this, or release latest build that supports java 18 and higher versions
